# Матрицы

**Матрица** — структура, представляющая собой таблицу, состоящую из чисел, расположенных по строкам и столбцам.


Числа, стоящие на пересечении строк и столбцов, называются **элементами матрицы**

Матрицу можно создать функцией `np.matrix()` или `np.array()`.

In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

В матрице четыре строки и три столбца. Говорят, что это матрица 4 x 3. За размерность матрицы отвечает атрибут `shape`:

In [3]:
A.shape

(4, 3)

## Классификация матриц по форме

#### Прямоугольные матрицы

Прямоугольные матрицы - те, у которых количество строк $n$ Не совпадает с количеством столбцов $m$, т.е. $n$ $\neq$ $m$

In [5]:
print('Ниже прямоугольная матрица')
M = np.array([
    [1, 34, -2], 
    [9, 4, 0]
])
M

Ниже прямоугольная матрица


array([[ 1, 34, -2],
       [ 9,  4,  0]])

#### Квадратные матрицы

Квадратные матрицы - те, у которых количество строк $ n $ совпадает с количеством столбцов $ m $, т.е. $ n $ $ = $ $ m $

In [8]:
print('Квадратная матрица:')
S = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
S

Квадратная матрица:


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Порядок матрицы

Порядок для квадртатной матрицы - количество строк / столбцов в ней

In [9]:
print('Квадратная матрица с порядком 2:')
S = np.array([
    [1, 2],
    [4, 5]
])
S

Квадратная матрица с порядком 2:


array([[1, 2],
       [4, 5]])

In [10]:
S[0]

array([1, 2])

#### Вектор-столбец

Вектор-столбец - матрица размера $(n, 1)$

$$
\begin{pmatrix}
1 \\
2 \\
3
\end{pmatrix}
$$

#### Вектор-строка

Вектор-строка - матрица размера $(1, m)$

#### Столбец и строка в `numpy`

# TODO
Сделать примечание про вектор-столбец, вектор-строку и обычный вектор в `numpy`

#### Вектор-столбец

Вектор-столбец - матрица размера $(n, 1)$

In [ ]:
print('Вектор-столбец:')
V = np.array([
    [1,],
    []
])