# Матрицы

**Матрица** — структура, представляющая собой таблицу, состоящую из чисел, расположенных по строкам и столбцам.


Числа, стоящие на пересечении строк и столбцов, называются **элементами матрицы**

Матрицу можно создать функцией `np.matrix()` или `np.array()`.

In [2]:
import numpy as np

In [2]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

В матрице четыре строки и три столбца. Говорят, что это матрица 4 x 3. За размерность матрицы отвечает атрибут `shape`:

In [3]:
A.shape

(4, 3)

## Классификация матриц по форме

#### Прямоугольные матрицы

Прямоугольные матрицы - те, у которых количество строк $n$ Не совпадает с количеством столбцов $m$, т.е. $n$ $\neq$ $m$

In [5]:
print('Ниже прямоугольная матрица')
M = np.array([
    [1, 34, -2], 
    [9, 4, 0]
])
M

Ниже прямоугольная матрица


array([[ 1, 34, -2],
       [ 9,  4,  0]])

#### Квадратные матрицы

Квадратные матрицы - те, у которых количество строк $ n $ совпадает с количеством столбцов $ m $, т.е. $ n $ $ = $ $ m $

In [8]:
print('Квадратная матрица:')
S = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
S

Квадратная матрица:


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Порядок матрицы

Порядок для квадртатной матрицы - количество строк / столбцов в ней

In [9]:
print('Квадратная матрица с порядком 2:')
S = np.array([
    [1, 2],
    [4, 5]
])
S

Квадратная матрица с порядком 2:


array([[1, 2],
       [4, 5]])

In [10]:
S[0]

array([1, 2])

#### Вектор-столбец

Вектор-столбец - матрица размера $(n, 1)$

$$
\begin{pmatrix}
1 \\
2 \\
3
\end{pmatrix}
$$

#### Вектор-строка

Вектор-строка - матрица размера $(1, m)$

$$
\begin{pmatrix}
1 & 2 & 3
\end{pmatrix}
$$

#### Столбец и строка в `numpy`

В `numpy` чаще всего мы используем понятие "вектор" как **одномерынй массив**: $(n,)$. Этот "обычный вектор" не является ли строкой, ни столбцом. 

Рассмотрим детальнее разницу между тремя понятиями:

**"обычный вектор" в `numpy`**

- математика: $(n, )$

- код:
    ```python
    np.array([1, 2, 3])
    ```

In [8]:
print(np.array([1, 2, 3]))
np.array([1, 2, 3])

[1 2 3]


array([1, 2, 3])

**вектор-строка в `numpy`**

- математика: $(1, 3)$

- код:
    ```python
    np.array([[1, 2, 3]])
    ```

In [9]:
print(np.array([[1, 2, 3]]))
np.array([[1, 2, 3]])

[[1 2 3]]


array([[1, 2, 3]])

**вектор-столбец в `numpy`**

- математика: $(3, 1)$

- код:
```python
np.array([[1], [2], [3]])
```

In [10]:
print(np.array([[1], [2], [3]]))
np.array([[1], [2], [3]])

[[1]
 [2]
 [3]]


array([[1],
       [2],
       [3]])

> ❗️ Популярные функции `numpy` поддерживают работу с форматом $(n,)$, он же `np.array([1, 2, 3])`. Но в матричных операциях и траспонировании, которые мы будем использовать, приходится использовать форму $(1, n)$ или $(n, 1)$ в зависимости от размерности матрицы  

## Классификация матриц по содержанию

#### Нулевая матрица

**Нулевая матрица** - та, у которой все элементы являются нулём. Формально это записывается так:

$$
A = (a_{ij}), \quad \forall a_{ij} = 0.
$$


In [11]:
print('Нулевая матрица:')
print(np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]]))

Нулевая матрица:
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### Матрица-единица, или матрица единиц

**Матрица-единица** - матрица, у которой все элементы являются единицей. Формально записываем так: 

$$
A = (a_{ij}), \quad \forall a_{ij} = 1.
$$

In [13]:
print('Матрица-единица:')
print(np.array([[1, 1], [1, 1], [1, 1]]))

Матрица-единица:
[[1 1]
 [1 1]
 [1 1]]


> Не путайте **матрицу-единицу** и **единичную** матрицу!

#### Треугольная матрица

**Треугольная матрица** - квадратная матрица, у которой элементы выше или ниже главной диагонали равны $0$

Формально мы можем записать так:

$$
A_{\text{ нижнетреугольная}} = (a_{ij}), \quad 
a_{ij} =
\begin{cases} 
a_{ij} \neq 0, & \text{при } i \geq j, \\
a_{ij} = 0, & \text{при } i < j
\end{cases}
$$
$$
A_{\text{ верхнетреугольная}} = (a_{ij}), \quad 
a_{ij} =
\begin{cases} 
a_{ij} = 0, & \text{при } i > j, \\
a_{ij} \neq 0, & \text{при } i \leq j
\end{cases}
$$

In [14]:
print('Треугольная матрица:')
print(np.array([[2, 0, 0], [1, -1, 0], [7.5, 8, 1]]))

Треугольная матрица:
[[ 2.   0.   0. ]
 [ 1.  -1.   0. ]
 [ 7.5  8.   1. ]]


#### Симметричная матрица

**Симметричная матрица** - квадратная матрица, у которой элементы равны друг другу относительно главной диагонали. 

Формальная запись:

$$
S = (s_{ij}), \quad s_{ij} = s_{ji} \, \forall i, j.
$$

In [24]:
print('Симметричная матрица:')
print(np.array([[2, -1, 15, 7], [-1, 16, -9, 0], 
                [15, -9, 10, 32], [7, 0, 32, 8]]))

Симметричная матрица:
[[ 2 -1 15  7]
 [-1 16 -9  0]
 [15 -9 10 32]
 [ 7  0 32  8]]


#### Диагональная матрица

**Диагональная матрица** - симметричная матрица, у которой вне главой диагонали стоят только $0$. 

Запишем её формально:

$$
S = (s_{ij}) = 
\begin{cases} 
s_{ij} = s_{ji} = 0, & \text{при } i \neq j, \\
s_{ij} \neq 0, & \text{при } i = j.
\end{cases}
$$

Диагональная матрица часто используется, поэтому есть более краткая запись:

$$
S = \operatorname{diag}(\alpha_1, \alpha_2, \dots, \alpha_n),
$$

$\alpha_i$ - элементы на главной диагонали

In [25]:
print('Диагональная матрица:')
print(np.array([[-9, 0, 0], [0, 5, 0], [0, 0, 127]]))

Диагональная матрица:
[[ -9   0   0]
 [  0   5   0]
 [  0   0 127]]


#### Скалярная матрица

**Скалярная матрица** - диагональная матрица, у которой по диагонали стоит одно и тоже число $ \alpha $ . Запишем формально:

$$
S = (s_{ij}) =
\begin{cases} 
s_{ij} = 0, & \text{при } i \neq j, \\
s_{ij} = \alpha, & \text{при } i = j.
\end{cases}
$$

Скалярная матрица также часто используется, поэтому у неё тоже есть краткая запись:

$$
S = \operatorname{diag}(\alpha)
$$

In [26]:
print('Скалярная матрица:')
print(np.array([[14, 0, 0], [0, 14, 0], [0, 0, 14]]))

Скалярная матрица:
[[14  0  0]
 [ 0 14  0]
 [ 0  0 14]]


#### Единичная матрица

**Единичная матрица** - скалярная матрица, у которой $\alpha = 1$. Единичная матрица настолько важная, что у неё есть специальное обозначение - латинская буква $E$

$$
E = (e_{ij}) =
\begin{cases} 
e_{ij} = 0, & \text{при } i \neq j, \\
e_{ij} = 1, & \text{при } i = j.
\end{cases}
$$

In [27]:
print('Единичная матрица:')
print(np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]))

Единичная матрица:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
